// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockManagement.Infrastructure.Persistence;

#nullable disable

namespace StockManagement.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001170920_AddArticleImageUrl")]
    partial class AddArticleImageUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamilleId")
                        .HasColumnType("uuid");

                    b.Property<bool>("GereVariantes")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("MarqueId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModeSuivi")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrixAchat")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SeuilMinimum")
                        .HasColumnType("integer");

                    b.Property<bool>("SuiviDatePeremption")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UniteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.HasIndex("MarqueId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("UniteId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ArticleVariante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeBarre")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("ReferenceVariante")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleVariantes");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ArticleVarianteValeur", b =>
                {
                    b.Property<Guid>("ArticleVarianteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ValeurAttributId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleVarianteId", "ValeurAttributId");

                    b.HasIndex("ValeurAttributId");

                    b.ToTable("ArticleVarianteValeurs");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.AttributVariante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("AttributsVariantes");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.AttributVarianteArticle", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributVarianteId")
                        .HasColumnType("uuid");

                    b.HasKey("ArticleId", "AttributVarianteId");

                    b.HasIndex("AttributVarianteId");

                    b.ToTable("AttributsVarianteArticles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Depot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Responsable")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Depots");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Famille", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FamilleParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("FamilleParentId");

                    b.ToTable("Familles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Fournisseur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Adresse")
                        .HasColumnType("text");

                    b.Property<string>("Contact")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EstActif")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telephone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Fournisseurs");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleVarianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateFabrication")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleVarianteId");

                    b.ToTable("Lots");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Marque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Marques");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.MouvementStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleVarianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateMouvement")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepotDestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepotSourceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid");

                    b.Property<string>("Motif")
                        .HasColumnType("text");

                    b.Property<Guid?>("MouvementLieId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NumeroSerieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<string>("UtilisateurNom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleVarianteId");

                    b.HasIndex("DepotDestinationId");

                    b.HasIndex("DepotSourceId");

                    b.HasIndex("LotId");

                    b.HasIndex("NumeroSerieId");

                    b.ToTable("MouvementsStock");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstLue")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DepotId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.NumeroSerie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleVarianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleVarianteId");

                    b.HasIndex("DepotId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("NumerosSerie");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ArticleVarianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepotId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LotId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantite")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ArticleVarianteId");

                    b.HasIndex("DepotId");

                    b.HasIndex("LotId");

                    b.ToTable("StockItems");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Unite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Unites");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ValeurAttribut", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributVarianteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EstSupprime")
                        .HasColumnType("boolean");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AttributVarianteId");

                    b.ToTable("ValeursAttributs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Famille", "Famille")
                        .WithMany("Articles")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.Marque", "Marque")
                        .WithMany("Articles")
                        .HasForeignKey("MarqueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Unite", "Unite")
                        .WithMany("Articles")
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Famille");

                    b.Navigation("Marque");

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ArticleVariante", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("Variantes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ArticleVarianteValeur", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.ArticleVariante", "ArticleVariante")
                        .WithMany("Valeurs")
                        .HasForeignKey("ArticleVarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ValeurAttribut", "ValeurAttribut")
                        .WithMany("VariantesAssociees")
                        .HasForeignKey("ValeurAttributId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArticleVariante");

                    b.Navigation("ValeurAttribut");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.AttributVarianteArticle", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("AttributsVariantes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.AttributVariante", "AttributVariante")
                        .WithMany("ArticlesAssocies")
                        .HasForeignKey("AttributVarianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("AttributVariante");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Famille", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Famille", "FamilleParent")
                        .WithMany("SousFamilles")
                        .HasForeignKey("FamilleParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FamilleParent");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Lot", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("Lots")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ArticleVariante", "ArticleVariante")
                        .WithMany("Lots")
                        .HasForeignKey("ArticleVarianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("ArticleVariante");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.MouvementStock", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ArticleVariante", "ArticleVariante")
                        .WithMany("Mouvements")
                        .HasForeignKey("ArticleVarianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Depot", "DepotDestination")
                        .WithMany()
                        .HasForeignKey("DepotDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Depot", "DepotSource")
                        .WithMany()
                        .HasForeignKey("DepotSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Lot", "Lot")
                        .WithMany("Mouvements")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.NumeroSerie", "NumeroSerie")
                        .WithMany("Mouvements")
                        .HasForeignKey("NumeroSerieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("ArticleVariante");

                    b.Navigation("DepotDestination");

                    b.Navigation("DepotSource");

                    b.Navigation("Lot");

                    b.Navigation("NumeroSerie");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Notification", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Depot", "Depot")
                        .WithMany()
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.NumeroSerie", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("NumerosSerie")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ArticleVariante", "ArticleVariante")
                        .WithMany("NumerosSerie")
                        .HasForeignKey("ArticleVarianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Depot", "Depot")
                        .WithMany("NumerosSerie")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("ArticleVariante");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.StockItem", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.Article", "Article")
                        .WithMany("StockItems")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.ArticleVariante", "ArticleVariante")
                        .WithMany("StockItems")
                        .HasForeignKey("ArticleVarianteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManagement.Domain.Entities.Depot", "Depot")
                        .WithMany("StockItems")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManagement.Domain.Entities.Lot", "Lot")
                        .WithMany("StockItems")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Article");

                    b.Navigation("ArticleVariante");

                    b.Navigation("Depot");

                    b.Navigation("Lot");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ValeurAttribut", b =>
                {
                    b.HasOne("StockManagement.Domain.Entities.AttributVariante", "AttributVariante")
                        .WithMany("Valeurs")
                        .HasForeignKey("AttributVarianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributVariante");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Article", b =>
                {
                    b.Navigation("AttributsVariantes");

                    b.Navigation("Lots");

                    b.Navigation("Mouvements");

                    b.Navigation("NumerosSerie");

                    b.Navigation("StockItems");

                    b.Navigation("Variantes");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ArticleVariante", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Mouvements");

                    b.Navigation("NumerosSerie");

                    b.Navigation("StockItems");

                    b.Navigation("Valeurs");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.AttributVariante", b =>
                {
                    b.Navigation("ArticlesAssocies");

                    b.Navigation("Valeurs");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Depot", b =>
                {
                    b.Navigation("NumerosSerie");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Famille", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("SousFamilles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Lot", b =>
                {
                    b.Navigation("Mouvements");

                    b.Navigation("StockItems");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Marque", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.NumeroSerie", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.Unite", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("StockManagement.Domain.Entities.ValeurAttribut", b =>
                {
                    b.Navigation("VariantesAssociees");
                });
#pragma warning restore 612, 618
        }
    }
}
